name: Superego Development Deployment
on:
  push:
    branches:
      - development
  pull_request:
    types:
      - closed
jobs:
  build:
      runs-on: ubuntu-latest
      
      steps:
        - name: Synchronise workspace
          uses: appleboy/ssh-action@v1.0.0
          with:
            # SSH host address.
            host: dev.allybros.com
            key: ${{ secrets.SEGODEVPK }}
            username: git-user
            script: |
              echo "Change working directory"
              cd /home/git-user/superego/superego-api
              pwd
              echo "Synchronise changes from git"
              git checkout development
              git reset --hard
              git fetch
              git pull origin development
            
        - name: Build docker image
          uses: appleboy/ssh-action@v1.0.0
          with:
            # SSH host address.
            host: dev.allybros.com
            key: ${{ secrets.SEGODEVPK }}
            username: git-user
            script: |
              echo "Change working directory"
              cd /home/git-user/superego/superego-api
              echo "Build image"
              sudo docker build .
            
        - name: Docker compose
          uses: appleboy/ssh-action@v1.0.0
          with:
            # SSH host address.
            host: dev.allybros.com
            key: ${{ secrets.SEGODEVPK }}
            username: git-user
            script: |
              echo "Change working directory"
              cd /home/git-user/superego/
              pwd
              echo "Compose deployment"
              sudo docker compose up -d

